FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build
WORKDIR /src

COPY ["Hermes.Domain/Hermes.Domain.csproj", "Hermes.Domain/"]
COPY ["Hermes.Infrastructure/Hermes.Infrastructure.csproj", "Hermes.Infrastructure/"]
COPY ["Hermes.WebFrontend/Hermes.WebFrontend/Hermes.WebFrontend.csproj", "Hermes.WebFrontend/Hermes.WebFrontend/"]
COPY ["Hermes.WebFrontend/Hermes.WebFrontend.Client/Hermes.WebFrontend.Client.csproj", "Hermes.WebFrontend/Hermes.WebFrontend.Client/"]

RUN dotnet restore "Hermes.WebFrontend/Hermes.WebFrontend/Hermes.WebFrontend.csproj"

COPY . .

RUN dotnet publish "Hermes.WebFrontend/Hermes.WebFrontend/Hermes.WebFrontend.csproj" \
    -c Release \
    -o /app/publish \
    /p:UseAppHost=false \
    /p:PublishStaticWebAssets=true

FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS final
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_HTTP_PORTS=7016
EXPOSE 7016

ENTRYPOINT ["dotnet", "Hermes.WebFrontend.dll"]