# Build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore "Hermes.Api/Hermes.Api.csproj"
WORKDIR /src/Hermes.Api
RUN dotnet publish -c Release -o /app/publish --no-restore

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 5165
ENV Urls=http://+:5165

ENTRYPOINT ["dotnet", "Hermes.Api.dll"]