services:
  hermes-mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025" # SMTP Port
      - "8025:8025" # Web UI Port

  hermes-mysql:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${MYSQL_PORT:-3308}:3306"
    volumes:
      - hermes_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s
    
  # hermes-migrate:
  #   image: docker-hermes-migrate
  #   build:
  #     context: ..
  #     dockerfile: Docker/Dockerfile.Migrate
  #   environment:
  #     ConnectionStrings__DefaultConnection: Server=hermes-mysql;Port=3306;Database=hermes;User=root;Password=password1234!;SslMode=none;
  #   depends_on:
  #     hermes-mysql:
  #       condition: service_healthy
  #   restart: "no"

  hermes-api:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile.Api
    ports:
      - "5165:5165"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=hermes-mysql;Port=3306;Database=hermes;User=root;Password=password1234!;SslMode=none;
      - Jwt__SigningKey=SuperSichererUndExtremLangerSchluessel123456!
    depends_on:
      hermes-mysql:
        condition: service_healthy
      # hermes-migrate:
      #   condition: service_completed_successfully

  hermes-worker:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile.Worker
    ports:
      - "5166:5166"
    volumes:
      - ../Hermes.Worker/.env:/app/.env:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=hermes-mysql;Port=3306;Database=hermes;User=root;Password=password1234!;SslMode=none;
      - Jwt__SigningKey=SuperSichererUndExtremLangerSchluessel123456!
      - Email__Host=hermes-mailhog
      - Email__Port=1025
      - MailHog__BaseUrl=http://hermes-mailhog:8025
    depends_on:
      hermes-mysql:
        condition: service_healthy
      # hermes-migrate:
      #   condition: service_completed_successfully
      hermes-mailhog:
        condition: service_started

  hermes-web:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.Web
    ports:
      - "7016:7016"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ApiBaseUrl=http://localhost:5165  
    depends_on:
      - hermes-api

volumes:
  hermes_data: