using Hermes.Domain.Enums;

namespace Hermes.WebFrontend.Client;

/// <summary>
/// German UI labels for domain enums (search + summary use the same strings).
/// </summary>
public static class NewsEnumGermanDisplay
{
    public static string CategoryDe(NewsCategory c) => c switch
    {
        NewsCategory.Breaking => "Eilmeldung",
        NewsCategory.Business => "Wirtschaft",
        NewsCategory.Crime => "Kriminalität",
        NewsCategory.Domestic => "Innenpolitik",
        NewsCategory.Education => "Bildung",
        NewsCategory.Entertainment => "Unterhaltung",
        NewsCategory.Environment => "Umwelt",
        NewsCategory.Food => "Essen & Trinken",
        NewsCategory.Health => "Gesundheit",
        NewsCategory.Lifestyle => "Lifestyle",
        NewsCategory.Other => "Sonstiges",
        NewsCategory.Politics => "Politik",
        NewsCategory.Science => "Wissenschaft",
        NewsCategory.Sports => "Sport",
        NewsCategory.Technology => "Technologie",
        NewsCategory.Top => "Top-Meldungen",
        NewsCategory.Tourism => "Tourismus",
        NewsCategory.World => "Welt",
        _ => c.ToString()
    };

    public static string LanguageDe(Language l) => l switch
    {
        Language.Albanian => "Albanisch",
        Language.Arabic => "Arabisch",
        Language.Armenian => "Armenisch",
        Language.Azerbaijani => "Aserbaidschanisch",
        Language.Basque => "Baskisch",
        Language.Belarusian => "Weißrussisch",
        Language.Bengali => "Bengalisch",
        Language.Bosnian => "Bosnisch",
        Language.Bulgarian => "Bulgarisch",
        Language.Catalan => "Katalanisch",
        Language.Chinese => "Chinesisch",
        Language.Croatian => "Kroatisch",
        Language.Czech => "Tschechisch",
        Language.Danish => "Dänisch",
        Language.Dutch => "Niederländisch",
        Language.English => "Englisch",
        Language.Estonian => "Estnisch",
        Language.Finnish => "Finnisch",
        Language.French => "Französisch",
        Language.Galician => "Galicisch",
        Language.German => "Deutsch",
        Language.Greek => "Griechisch",
        Language.Hebrew => "Hebräisch",
        Language.Hindi => "Hindi",
        Language.Hungarian => "Ungarisch",
        Language.Icelandic => "Isländisch",
        Language.Indonesian => "Indonesisch",
        Language.Irish => "Irisch",
        Language.Italian => "Italienisch",
        Language.Japanese => "Japanisch",
        Language.Korean => "Koreanisch",
        Language.Latvian => "Lettisch",
        Language.Lithuanian => "Litauisch",
        Language.Macedonian => "Mazedonisch",
        Language.Maltese => "Maltesisch",
        Language.Malay => "Malaiisch",
        Language.Norwegian => "Norwegisch",
        Language.Persian => "Persisch (Farsi)",
        Language.Polish => "Polnisch",
        Language.Portuguese => "Portugiesisch",
        Language.Romanian => "Rumänisch",
        Language.Russian => "Russisch",
        Language.Serbian => "Serbisch",
        Language.Slovak => "Slowakisch",
        Language.Slovenian => "Slowenisch",
        Language.Spanish => "Spanisch",
        Language.Swedish => "Schwedisch",
        Language.Thai => "Thailändisch",
        Language.Turkish => "Türkisch",
        Language.Ukrainian => "Ukrainisch",
        Language.Urdu => "Urdu",
        Language.Vietnamese => "Vietnamesisch",
        Language.Welsh => "Walisisch",
        _ => l.ToString()
    };

    public static string CountryDe(Country c) => c switch
    {
        Country.Albania => "Albanien",
        Country.Andorra => "Andorra",
        Country.Austria => "Österreich",
        Country.Belarus => "Belarus",
        Country.Belgium => "Belgien",
        Country.BosniaHerzegovina => "Bosnien und Herzegowina",
        Country.Bulgaria => "Bulgarien",
        Country.Croatia => "Kroatien",
        Country.Cyprus => "Zypern",
        Country.CzechRepublic => "Tschechien",
        Country.Denmark => "Dänemark",
        Country.Estonia => "Estland",
        Country.Finland => "Finnland",
        Country.France => "Frankreich",
        Country.Germany => "Deutschland",
        Country.Greece => "Griechenland",
        Country.Hungary => "Ungarn",
        Country.Iceland => "Island",
        Country.Ireland => "Irland",
        Country.Italy => "Italien",
        Country.Kosovo => "Kosovo",
        Country.Latvia => "Lettland",
        Country.Liechtenstein => "Liechtenstein",
        Country.Lithuania => "Litauen",
        Country.Luxembourg => "Luxemburg",
        Country.Malta => "Malta",
        Country.Moldova => "Moldau",
        Country.Monaco => "Monaco",
        Country.Montenegro => "Montenegro",
        Country.Netherlands => "Niederlande",
        Country.NorthMacedonia => "Nordmazedonien",
        Country.Norway => "Norwegen",
        Country.Poland => "Polen",
        Country.Portugal => "Portugal",
        Country.Romania => "Rumänien",
        Country.Russia => "Russland",
        Country.SanMarino => "San Marino",
        Country.Serbia => "Serbien",
        Country.Slovakia => "Slowakei",
        Country.Slovenia => "Slowenien",
        Country.Spain => "Spanien",
        Country.Sweden => "Schweden",
        Country.Switzerland => "Schweiz",
        Country.Ukraine => "Ukraine",
        Country.UnitedKingdom => "Vereinigtes Königreich",
        Country.VaticanCity => "Vatikanstadt",
        Country.China => "China",
        Country.Japan => "Japan",
        Country.Mexico => "Mexiko",
        Country.SouthKorea => "Südkorea",
        Country.USA => "USA",
        Country.Argentina => "Argentinien",
        Country.Armenia => "Armenien",
        Country.Australia => "Australien",
        Country.Azerbaijan => "Aserbaidschan",
        Country.Bangladesh => "Bangladesch",
        Country.Brazil => "Brasilien",
        Country.Canada => "Kanada",
        Country.Chile => "Chile",
        Country.Colombia => "Kolumbien",
        Country.Egypt => "Ägypten",
        Country.Georgia => "Georgien",
        Country.India => "Indien",
        Country.Indonesia => "Indonesien",
        Country.Israel => "Israel",
        Country.Malaysia => "Malaysia",
        Country.NewZealand => "Neuseeland",
        Country.Nigeria => "Nigeria",
        Country.Pakistan => "Pakistan",
        Country.Philippines => "Philippinen",
        Country.SaudiArabia => "Saudi-Arabien",
        Country.Singapore => "Singapur",
        Country.SouthAfrica => "Südafrika",
        Country.Taiwan => "Taiwan",
        Country.Thailand => "Thailand",
        Country.Turkey => "Türkei",
        Country.UnitedArabEmirates => "Vereinigte Arabische Emirate",
        Country.Vietnam => "Vietnam",
        _ => c.ToString()
    };
}
