<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Hermes.Notifications</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Sending\HtmlLayout\Templates\NewsletterHeader.html" />
    <EmbeddedResource Include="Sending\HtmlLayout\Templates\NewsletterItem.html" />
    <EmbeddedResource Include="Sending\HtmlLayout\Templates\NewsletterFooter.html" />
    <EmbeddedResource Include="Sending\HtmlLayout\Templates\Verification.html" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hermes.Application\Hermes.Application.csproj" />
  </ItemGroup>

</Project>

